#!/usr/bin/env php
<?php
require_once __DIR__.'/bootstrap.php';
require_once VENDOR_DIR.'SimpleAmazon/SimpleAmazonDynamoDB.php';
require_once CONFIG_DIR.'dynamo.php';
require_once CONFIG_DIR.'aws_sts_key.php';

function main($argc, $argv)
{
    $db = Dynamo::conn();
    $r = $db->call('ListTables');
    if ($db->status_code != 200) {
        print_r($r);
        exit(1);
    }
    foreach ($r['TableNames'] as $table_name) {
        $r = $db->call('DescribeTable', array('TableName' => $table_name));
        if ($db->status_code != 200) {
            print_r($r);
            exit(1);
        }
        var_dump($r);
    }

}

main($argc, $argv);
